name: Deploy Docs

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name:
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        run: cd documentation && npm run deploy
