name: Deploy Docs

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GIT_USER: ${{ secrets.USER }}
      GIT_PASS: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name:
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Deps
        run: |
          cd documentation
          npm i

      - name: Deploy
        run: cd documentation && npm run deploy
