name: Deploy Docs

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    # env:
    # GIT_USER: ${{ secrets.USER }}
    # GIT_PASS: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name:
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Deps
        run: |
          cd documentation
          npm i

      # - name: Deploy
      # run: |
      # export ORG_NAME=$(echo ${GITHUB_REPOSITORY%/*})
      # export PROJECT_NAME=$(echo ${GITHUB_REPOSITORY#*/})
      # git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
      # git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
      # cd documentation && npm run deploy

      - name: Deploy to GitHub Pages
        run: |
          GIT_USER=${{ github.actor }} \
          USE_SSH=false \
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
